name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show repo contents
        run: |
          echo "Listing files to debug path issue..."
          ls -R

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -f Week5/webdriver_java/pom.xml

      - name: Run tests
        run: mvn -f Week5/webdriver_java/pom.xml test
